export const SPIN_WHEEL_ABI = [
  {
    type: "function",
    name: "createSession",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "closeSession",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimSpin",
    inputs: [
      { name: "sessionId", type: "bytes32" },
      { name: "amount", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getSession",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [
      { name: "host", type: "address" },
      { name: "isActive", type: "bool" },
      { name: "isExpired", type: "bool" },
      { name: "prizePool", type: "uint256" },
      { name: "expiresAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidSigner", inputs: [] },
  { type: "error", name: "SessionAlreadyExists", inputs: [{ name: "sessionId", type: "bytes32" }] },
  { type: "error", name: "SessionNotFound", inputs: [{ name: "sessionId", type: "bytes32" }] },
  { type: "error", name: "SessionNotActive", inputs: [{ name: "sessionId", type: "bytes32" }] },
  { type: "error", name: "AlreadyClaimed", inputs: [{ name: "sessionId", type: "bytes32" }, { name: "player", type: "address" }] },
  { type: "error", name: "InsufficientPool", inputs: [{ name: "available", type: "uint256" }, { name: "requested", type: "uint256" }] },
  { type: "error", name: "ClaimExpired", inputs: [{ name: "sessionId", type: "bytes32" }] },
  { type: "error", name: "TransferFailed", inputs: [{ name: "recipient", type: "address" }, { name: "amount", type: "uint256" }] },
  { type: "error", name: "ZeroDeposit", inputs: [] },
] as const;
